// Phase 0: hand-written IPC types. Phase 1 replaces these with bindings
// auto-generated by `tauri-specta` (output path: ./bindings.ts), keeping
// the Rust types in `crates/core` as the single source of truth.

export type AgentCli = "copilot" | "claude-code" | "gemini";

export interface Greeting {
  agentName: string;
  agentVersion: string;
}
