//! Save / delete canonical agents and write the per-CLI transpiled artifacts.
//!
//! The canonical document under `~/.senda/agents/<name>.agent.md` is the
//! source of truth. For every CLI in `targets:` we transpile and write the
//! native file. A small `manifest.json` records which native files were
//! generated by which canonical doc so we can clean up orphans.

use std::collections::HashMap;
use std::path::PathBuf;
use std::time::{SystemTime, UNIX_EPOCH};

use senda_agent_parser::{
    parse_canonical, serialize_canonical,
    transpilers::{for_cli, TranspileOutput},
};
use senda_core::{AgentCli, CanonicalAgent};
use serde::{Deserialize, Serialize};
use tauri::{AppHandle, Emitter};

#[derive(Debug, Clone, Serialize, Deserialize, specta::Type)]
#[serde(rename_all = "camelCase")]
pub struct SaveAgentArgs {
    /// Original agent name — used to detect renames so we can delete the
    /// previous artifacts. None for fresh creations.
    pub previous_name: Option<String>,
    /// Raw canonical document text.
    pub source: String,
    #[serde(default)]
    pub draft: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize, specta::Type)]
#[serde(rename_all = "camelCase")]
pub struct SaveAgentResult {
    pub canonical_path: String,
    pub generated: Vec<String>,
    pub warnings: Vec<TranspileWarning>,
}

#[derive(Debug, Clone, Serialize, Deserialize, specta::Type)]
#[serde(rename_all = "camelCase")]
pub struct TranspileWarning {
    pub target: AgentCli,
    pub field_path: String,
    pub message: String,
}

#[tauri::command]
pub async fn save_agent(app: AppHandle, args: SaveAgentArgs) -> Result<SaveAgentResult, String> {
    let canonical = parse_canonical(&args.source).map_err(|e| format!("parse: {e}"))?;
    if canonical.targets.is_empty() {
        return Err("targets must contain at least one CLI".into());
    }

    let home = dirs::home_dir().ok_or_else(|| "no home".to_string())?;
    let senda_root = home.join(".senda");
    let agents_dir = if args.draft {
        senda_root.join("drafts")
    } else {
        senda_root.join("agents")
    };
    std::fs::create_dir_all(&agents_dir).map_err(|e| format!("mkdir: {e}"))?;

    // Re-serialize so we end up with a normalized canonical document on disk.
    let serialized = serialize_canonical(&canonical).map_err(|e| format!("serialize: {e}"))?;
    let canonical_path = agents_dir.join(format!("{}.agent.md", canonical.name));
    std::fs::write(&canonical_path, &serialized).map_err(|e| format!("write canonical: {e}"))?;

    // Clean up artifacts from a previous name if this was a rename.
    if let Some(prev) = args.previous_name.as_deref() {
        if prev != canonical.name {
            let prev_canonical = agents_dir.join(format!("{prev}.agent.md"));
            let _ = std::fs::remove_file(prev_canonical);
            for cli in AgentCli::ALL {
                let _ = std::fs::remove_file(
                    home.join(cli.agents_dir())
                        .join(format!("{prev}.{}", cli.agent_extension())),
                );
            }
        }
    }

    let mut generated = Vec::new();
    let mut warnings = Vec::new();
    if !args.draft {
        let (gens, warns) = write_artifacts(&home, &canonical)?;
        generated = gens;
        warnings = warns;
    }
    update_manifest(&senda_root, &canonical.name, &generated)?;

    let _ = app.emit("agents:changed", ());
    Ok(SaveAgentResult {
        canonical_path: canonical_path.to_string_lossy().to_string(),
        generated,
        warnings,
    })
}

#[tauri::command]
pub async fn delete_agent(app: AppHandle, name: String, draft: Option<bool>) -> Result<(), String> {
    let home = dirs::home_dir().ok_or_else(|| "no home".to_string())?;
    let senda_root = home.join(".senda");
    let agents_dir = if draft.unwrap_or(false) {
        senda_root.join("drafts")
    } else {
        senda_root.join("agents")
    };
    let canonical = agents_dir.join(format!("{name}.agent.md"));
    let _ = std::fs::remove_file(&canonical);
    for cli in AgentCli::ALL {
        let _ = std::fs::remove_file(
            home.join(cli.agents_dir())
                .join(format!("{name}.{}", cli.agent_extension())),
        );
    }
    update_manifest(&senda_root, &name, &[])?;
    let _ = app.emit("agents:changed", ());
    Ok(())
}

#[tauri::command]
pub async fn list_drafts() -> Result<Vec<String>, String> {
    let home = dirs::home_dir().ok_or_else(|| "no home".to_string())?;
    let drafts = home.join(".senda").join("drafts");
    if !drafts.is_dir() {
        return Ok(Vec::new());
    }
    let mut out = Vec::new();
    for entry in std::fs::read_dir(&drafts).map_err(|e| format!("read drafts: {e}"))? {
        let Ok(entry) = entry else { continue };
        let path = entry.path();
        if path
            .file_name()
            .and_then(|n| n.to_str())
            .is_some_and(|n| n.ends_with(".agent.md"))
        {
            out.push(path.to_string_lossy().to_string());
        }
    }
    Ok(out)
}

#[tauri::command]
pub async fn read_agent_source(canonical_path: String) -> Result<String, String> {
    std::fs::read_to_string(&canonical_path).map_err(|e| format!("read: {e}"))
}

// ── helpers ─────────────────────────────────────────────────────────────────

fn write_artifacts(
    home: &std::path::Path,
    canonical: &CanonicalAgent,
) -> Result<(Vec<String>, Vec<TranspileWarning>), String> {
    let mut generated = Vec::new();
    let mut warnings = Vec::new();
    for &cli in &canonical.targets {
        let dir = home.join(cli.agents_dir());
        std::fs::create_dir_all(&dir).map_err(|e| format!("mkdir {cli:?}: {e}"))?;
        let TranspileOutput {
            filename,
            contents,
            warnings: ws,
        } = for_cli(cli).transpile(canonical);
        let file = dir.join(&filename);
        std::fs::write(&file, &contents).map_err(|e| format!("write {filename}: {e}"))?;
        generated.push(file.to_string_lossy().to_string());
        for w in ws {
            warnings.push(TranspileWarning {
                target: w.target,
                field_path: w.field_path,
                message: w.message,
            });
        }
    }
    Ok((generated, warnings))
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
struct Manifest {
    /// Canonical name → list of generated file paths.
    pub agents: HashMap<String, ManifestEntry>,
    pub updated_at: i64,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
struct ManifestEntry {
    pub generated: Vec<String>,
    pub last_written: i64,
}

fn update_manifest(
    senda_root: &std::path::Path,
    name: &str,
    generated: &[String],
) -> Result<(), String> {
    let path: PathBuf = senda_root.join("manifest.json");
    let mut manifest: Manifest = std::fs::read_to_string(&path)
        .ok()
        .and_then(|s| serde_json::from_str(&s).ok())
        .unwrap_or_default();
    if generated.is_empty() {
        manifest.agents.remove(name);
    } else {
        manifest.agents.insert(
            name.to_string(),
            ManifestEntry {
                generated: generated.to_vec(),
                last_written: unix_now(),
            },
        );
    }
    manifest.updated_at = unix_now();
    let serialized =
        serde_json::to_string_pretty(&manifest).map_err(|e| format!("manifest: {e}"))?;
    std::fs::write(&path, serialized).map_err(|e| format!("manifest write: {e}"))
}

fn unix_now() -> i64 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_secs() as i64)
        .unwrap_or(0)
}
